"""add user profile verification fields

Revision ID: 3a4104025ab6
Revises: 5847bfa1b91d
Create Date: 2026-09-15 08:42:10.666594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a4104025ab6'
down_revision = '5847bfa1b91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_tokens_token'), ['token'], unique=True)

    op.create_table('portfolio_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('gig_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gig_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'gig_id', name='uq_saved_user_gig')
    )
    with op.batch_alter_table('gigs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_type', sa.Enum('FIXED', 'NEGOTIABLE', name='pricetype'), nullable=False))
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deliverables', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_gigs_price_type'), ['price_type'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_generated', sa.Boolean(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hostel_location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_verified_student', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('whatsapp_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('whatsapp_phone', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('hide_phone_number', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_hostel_location'), ['hostel_location'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_hostel_location'))
        batch_op.drop_column('hide_phone_number')
        batch_op.drop_column('whatsapp_phone')
        batch_op.drop_column('whatsapp_verified')
        batch_op.drop_column('is_verified_student')
        batch_op.drop_column('hostel_location')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('auto_generated')

    with op.batch_alter_table('gigs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gigs_price_type'))
        batch_op.drop_column('deliverables')
        batch_op.drop_column('deadline')
        batch_op.drop_column('price_type')

    op.drop_table('saved_listings')
    op.drop_table('portfolio_images')
    with op.batch_alter_table('verification_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_tokens_token'))

    op.drop_table('verification_tokens')
    # ### end Alembic commands ###
