"""second migration

Revision ID: 5847bfa1b91d
Revises: 9fe2c73d8985
Create Date: 2026-09-12 09:52:07.505095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5847bfa1b91d'
down_revision = '9fe2c73d8985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gigs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('landmark', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('slots_needed', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('slots_filled', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('completed_by_poster', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('completed_by_counterparty', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('completion_requested_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('disputed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('dispute_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('disputed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('flagged_for_review', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('flag_reason', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['disputed_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method', sa.Enum('MANUAL', 'STK_PUSH', 'CREDIT', name='paymentmethod'), nullable=False))
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('merchant_request_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=True))
        batch_op.alter_column('mpesa_code',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_payments_checkout_request_id'), ['checkout_request_id'], unique=True)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_generated', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('referred_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('free_boost_credits', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_users_is_admin')
        batch_op.create_unique_constraint(None, ['referral_code'])
        batch_op.create_foreign_key(None, 'users', ['referred_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_users_is_admin', ['is_admin'], unique=False)
        batch_op.drop_column('free_boost_credits')
        batch_op.drop_column('referred_by_id')
        batch_op.drop_column('referral_code')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_checkout_request_id'))
        batch_op.alter_column('mpesa_code',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
        batch_op.drop_column('phone_number')
        batch_op.drop_column('merchant_request_id')
        batch_op.drop_column('checkout_request_id')
        batch_op.drop_column('method')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('auto_generated')

    with op.batch_alter_table('gigs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('flag_reason')
        batch_op.drop_column('flagged_for_review')
        batch_op.drop_column('disputed_by_id')
        batch_op.drop_column('dispute_reason')
        batch_op.drop_column('disputed')
        batch_op.drop_column('completion_requested_at')
        batch_op.drop_column('completed_by_counterparty')
        batch_op.drop_column('completed_by_poster')
        batch_op.drop_column('slots_filled')
        batch_op.drop_column('slots_needed')
        batch_op.drop_column('landmark')

    # ### end Alembic commands ###
